In [60]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
#importing the dataset

train = pd.read_csv("Downloads/SpaceShip Titanic/train.csv")

print(train.head())


  PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True  


In [18]:
#counting null values

train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [19]:
print(train.PassengerId.count())

8693


In [20]:
print(pd.get_dummies(train.Cabin))

      A/0/P  A/0/S  A/1/S  A/10/P  A/10/S  A/100/S  A/101/S  A/102/S  A/103/S  \
0         0      0      0       0       0        0        0        0        0   
1         0      0      0       0       0        0        0        0        0   
2         0      1      0       0       0        0        0        0        0   
3         0      1      0       0       0        0        0        0        0   
4         0      0      0       0       0        0        0        0        0   
...     ...    ...    ...     ...     ...      ...      ...      ...      ...   
8688      0      0      0       0       0        0        0        0        0   
8689      0      0      0       0       0        0        0        0        0   
8690      0      0      0       0       0        0        0        0        0   
8691      0      0      0       0       0        0        0        0        0   
8692      0      0      0       0       0        0        0        0        0   

      A/104/S  ...  G/996/S

In [21]:
print(pd.get_dummies(train.Destination))

      55 Cancri e  PSO J318.5-22  TRAPPIST-1e
0               0              0            1
1               0              0            1
2               0              0            1
3               0              0            1
4               0              0            1
...           ...            ...          ...
8688            1              0            0
8689            0              1            0
8690            0              0            1
8691            1              0            0
8692            0              0            1

[8693 rows x 3 columns]


In [22]:
print(pd.get_dummies(train.HomePlanet))

In [32]:
colonne = ["Age","RoomService","FoodCourt","ShoppingMall","Spa","VRDeck"]

In [39]:
train =transform_data(train)

In [44]:
print(train)

     PassengerId CryoSleep     Cabin    Destination   Age    VIP  RoomService  \
0        0001_01     False     B/0/P    TRAPPIST-1e  39.0  False          0.0   
1        0002_01     False     F/0/S    TRAPPIST-1e  24.0  False        109.0   
2        0003_01     False     A/0/S    TRAPPIST-1e  58.0   True         43.0   
3        0003_02     False     A/0/S    TRAPPIST-1e  33.0  False          0.0   
4        0004_01     False     F/1/S    TRAPPIST-1e  16.0  False        303.0   
...          ...       ...       ...            ...   ...    ...          ...   
8688     9276_01     False    A/98/P    55 Cancri e  41.0   True          0.0   
8689     9278_01      True  G/1499/S  PSO J318.5-22  18.0  False          0.0   
8690     9279_01     False  G/1500/S    TRAPPIST-1e  26.0  False          0.0   
8691     9280_01     False   E/608/S    55 Cancri e  32.0  False          0.0   
8692     9280_02     False   E/608/S    TRAPPIST-1e  44.0  False        126.0   

      FoodCourt  ShoppingMa

In [94]:
train = pd.get_dummies(train, prefix='', prefix_sep='', 
                            columns=["HomePlanet"])

train.Destination.replace(['55 Cancri e', 'PSO J318.5-22','TRAPPIST-1e'],
                             [0,1,2], inplace=True)

train.CryoSleep.replace([False,True,'nan'],[0,1,'nan'], inplace=True)

In [59]:
print(train.head())

  PassengerId CryoSleep  Cabin  Destination   Age    VIP  RoomService  \
0     0001_01      None  B/0/P          2.0  39.0  False          0.0   
1     0002_01      None  F/0/S          2.0  24.0  False        109.0   
2     0003_01      None  A/0/S          2.0  58.0   True         43.0   
3     0003_02      None  A/0/S          2.0  33.0  False          0.0   
4     0004_01      None  F/1/S          2.0  16.0  False        303.0   

   FoodCourt  ShoppingMall     Spa  VRDeck               Name  Transported  \
0        0.0           0.0     0.0     0.0    Maham Ofracculy        False   
1        9.0          25.0   549.0    44.0       Juanna Vines         True   
2     3576.0           0.0  6715.0    49.0      Altark Susent        False   
3     1283.0         371.0  3329.0   193.0       Solam Susent        False   
4       70.0         151.0   565.0     2.0  Willy Santantines         True   

   Earth  Europa  Mars  
0      0       1     0  
1      1       0     0  
2      0       1 

In [67]:
train.CryoSleep.unique()

array([ 0.,  1., nan])

In [68]:
train.VIP.replace([False,True],
                             [0,1], inplace=True)
    

In [69]:
train.VIP.unique()

array([ 0.,  1., nan])

In [71]:
train.Transported.replace([False,True],
                             [0,1], inplace=True)

In [72]:
train.Transported.unique()

array([0, 1], dtype=int64)

In [73]:
train[["Cab_deck","Cab_num","Cab_side"]] = train['Cabin'].str.split('/', expand=True)

In [75]:
print(train)

     PassengerId HomePlanet  CryoSleep     Cabin    Destination   Age  VIP  \
0        0001_01     Europa        0.0     B/0/P    TRAPPIST-1e  39.0  0.0   
1        0002_01      Earth        0.0     F/0/S    TRAPPIST-1e  24.0  0.0   
2        0003_01     Europa        0.0     A/0/S    TRAPPIST-1e  58.0  1.0   
3        0003_02     Europa        0.0     A/0/S    TRAPPIST-1e  33.0  0.0   
4        0004_01      Earth        0.0     F/1/S    TRAPPIST-1e  16.0  0.0   
...          ...        ...        ...       ...            ...   ...  ...   
8688     9276_01     Europa        0.0    A/98/P    55 Cancri e  41.0  1.0   
8689     9278_01      Earth        1.0  G/1499/S  PSO J318.5-22  18.0  0.0   
8690     9279_01      Earth        0.0  G/1500/S    TRAPPIST-1e  26.0  0.0   
8691     9280_01     Europa        0.0   E/608/S    55 Cancri e  32.0  0.0   
8692     9280_02     Europa        0.0   E/608/S    TRAPPIST-1e  44.0  0.0   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck     

In [76]:
train.Cab_deck.unique()

array(['B', 'F', 'A', 'G', nan, 'E', 'D', 'C', 'T'], dtype=object)

In [84]:
train.Cab_side.replace(['P', 'S'],
                             [0,1], inplace=True)

In [80]:
for column in colonne:
        train[column] = train[column]  / train[column].abs().max()

In [85]:
print(train)

In [87]:
train.drop("Cabin",axis=1,inplace=True)

In [88]:
train.drop("PassengerId",axis=1,inplace=True)
train.drop("Name",axis=1,inplace=True)

In [95]:
print(train)

      CryoSleep  Destination       Age  VIP  RoomService  FoodCourt  \
0           0.0          2.0  0.493671  0.0     0.000000   0.000000   
1           0.0          2.0  0.303797  0.0     0.007608   0.000302   
2           0.0          2.0  0.734177  1.0     0.003001   0.119948   
3           0.0          2.0  0.417722  0.0     0.000000   0.043035   
4           0.0          2.0  0.202532  0.0     0.021149   0.002348   
...         ...          ...       ...  ...          ...        ...   
8688        0.0          0.0  0.518987  1.0     0.000000   0.228726   
8689        1.0          1.0  0.227848  0.0     0.000000   0.000000   
8690        0.0          2.0  0.329114  0.0     0.000000   0.000000   
8691        0.0          0.0  0.405063  0.0     0.000000   0.035186   
8692        0.0          2.0  0.556962  0.0     0.008795   0.157247   

      ShoppingMall       Spa    VRDeck  Transported  Cab_deck Cab_num  \
0         0.000000  0.000000  0.000000            0       0.0       0   
1

In [97]:
from sklearn.impute import SimpleImputer

In [105]:
train.dropna(inplace=True)

In [170]:
from sklearn.model_selection import train_test_split

X = train[["CryoSleep","Destination","Age","VIP",
           "RoomService","FoodCourt","ShoppingMall","Spa","VRDeck","Cab_deck","Cab_num","Cab_side",
           "Earth","Europa","Mars"]]
y = train[["Transported"]]    

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

In [172]:
from sklearn.svm import SVC

model = SVC(kernel='linear',C=3)

model.fit(X_train,y_train)

C:\Users\danie\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=3, kernel='linear')

In [173]:
accuracy = model.score(X_test,y_test)
print(accuracy)

0.7555875991348233


In [155]:
test = pd.read_csv("Downloads/SpaceShip Titanic/test.csv")

In [152]:
id = test.PassengerId

In [131]:
print(test)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False   
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False   
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False   
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False   
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False   
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False   
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False   
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False   
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa 

In [153]:
test.count()

PassengerId     4277
HomePlanet      4190
CryoSleep       4184
Cabin           4177
Destination     4185
Age             4186
VIP             4184
RoomService     4195
FoodCourt       4171
ShoppingMall    4179
Spa             4176
VRDeck          4197
Name            4183
dtype: int64

In [156]:
for colonna in colonne:
    mean_value = test[colonna].mean()
    test[colonna].fillna(value=mean_value, inplace=True)
    
print(test.isnull().sum())

PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age               0
VIP              93
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name             94
dtype: int64


In [157]:
test.bfill(axis=None, inplace=True, limit=None, downcast=None)
print(test.isnull().sum())

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
dtype: int64


In [158]:
#transform test dataset

test = pd.get_dummies(test, prefix='', prefix_sep='', 
                            columns=["HomePlanet"])

In [159]:
test.Destination.replace(['55 Cancri e', 'PSO J318.5-22','TRAPPIST-1e'],
                             [0,1,2], inplace=True)

test.CryoSleep.replace([False,True,'nan'],[0,1,'nan'], inplace=True)

test.VIP.replace([False,True],
                             [0,1], inplace=True)

test[["Cab_deck","Cab_num","Cab_side"]] = test['Cabin'].str.split('/', expand=True)

test.Cab_side.replace(['P', 'S'],
                             [0,1], inplace=True)

for column in colonne:
        test[column] = test[column]  / test[column].abs().max()
        
test.drop("Cabin",axis=1,inplace=True)

test.drop("PassengerId",axis=1,inplace=True)

test.drop("Name",axis=1,inplace=True)

In [165]:
test.Cab_deck.replace(['B', 'F', 'A', 'G', 'E', 'D', 'C', 'T'],
                             [0,1,2,3,4,5,6,7], inplace=True)
    
test.Cab_side.replace(['P', 'S'],
                             [0,1], inplace=True)

In [166]:
print(test)

      CryoSleep  Destination       Age  VIP  RoomService  FoodCourt  \
0             1            2  0.341772    0     0.000000   0.000000   
1             0            2  0.240506    0     0.000000   0.000356   
2             1            0  0.392405    0     0.000000   0.000000   
3             0            2  0.481013    0     0.000000   0.263206   
4             0            2  0.253165    0     0.000865   0.000000   
...         ...          ...       ...  ...          ...        ...   
4272          1            2  0.430380    0     0.000000   0.000000   
4273          0            2  0.531646    0     0.000000   0.033514   
4274          1            0  0.362761    0     0.000000   0.000000   
4275          0            1  0.362761    0     0.000000   0.106042   
4276          1            1  0.544304    0     0.000000   0.000000   

      ShoppingMall       Spa    VRDeck  Earth  Europa  Mars  Cab_deck Cab_num  \
0          0.00000  0.000000  0.000000      1       0     0       

In [174]:
result = model.predict(test)
print(result)

[1 1 1 ... 1 1 1]


C:\Users\danie\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


In [184]:
print(id.shape)
print(result.shape)

In [200]:
predictions= pd.DataFrame({"PassengerId":id,"Survived":result}, columns = ['PassengerId','Survived'])

In [201]:
print(predictions)

     PassengerId  Survived
0        0013_01         1
1        0018_01         1
2        0019_01         1
3        0021_01         0
4        0023_01         1
...          ...       ...
4272     9266_02         1
4273     9269_01         1
4274     9271_01         1
4275     9273_01         1
4276     9277_01         1

[4277 rows x 2 columns]


In [202]:
predictions.Survived.replace([0,1],
                             [False,True], inplace=True)

print(predictions)

     PassengerId  Survived
0        0013_01      True
1        0018_01      True
2        0019_01      True
3        0021_01     False
4        0023_01      True
...          ...       ...
4272     9266_02      True
4273     9269_01      True
4274     9271_01      True
4275     9273_01      True
4276     9277_01      True

[4277 rows x 2 columns]


In [197]:
predictions = predictions.reset_index(drop=True, inplace=True)

In [203]:
predictions.to_csv('Downloads/SpaceShip Titanic/predictions.csv',index=False)